### ISSUE TITLE
`create_user` fails if `HashidsField` is set on the User model

### ISSUE THREAD

**Issue by ndrbrt** [ericls/django-hashids#2] opened 2020-07-13 10:31 UTC
I tried to add an hashid field to my custom user model and it fails when I try to create a new user.

My custom user model:
```python
class User(AbstractUser):
    hashid = HashidsField(real_field_name='id')
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
```

The error:
```bash
======================================================================
ERROR: test_create_user (users.tests.UsersManagersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<...>/mysite/users/tests.py", line 9, in test_create_user
    user = User.objects.create_user(email='normal@user.com', password='foo')
  File "<...>/mysite/users/managers.py", line 18, in create_user
    user = self.model(email=email, **extra_fields)
  File "<...>/lib/python3.8/site-packages/django/db/models/base.py", line 485, in __init__
    _setattr(self, field.attname, val)
  File "<...>/lib/python3.8/site-packages/django_hashids/field.py", line 100, in __set__
    raise AttributeError("HashidsField is read only")
AttributeError: HashidsField is read only
```

I was able to solve the problem only by passing `hashid=django.db.models.DEFERRED` to `create_user`: `User.objects.create_user('foo@bar.com', 'password', hashid=django.db.models.DEFERRED)`. (Actually, I put the `hashid=django.db.models.DEFERRED` directly in my `CustomUserManager`)

So, is that the intended behaviour or maybe there's a better solution?

**Comment by ericls** [comment] 2020-07-14 00:31
@ndrbrt thanks for the report.

I think the issue is that I was setting `HashidsField.column` to empty string instead of None. Should be fixed in #3

**Closed** 2020-07-14 02:42 UTC
